apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-continuous-delivery
  labels:
    app: sprint-boot-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-boot-deployment
    spec:
      containers:
      - name: spring-boot-continuous-delivery
        image: docker.io/jzaccone/spring-boot-continuous-delivery
        ports:
          - containerPort: 9080
        imagePullPolicy: Always
        volumeMounts:
        - name: cloudant-secrets
          mountPath: /etc/cloudant-secrets
          readOnly: true
      volumes:
      - name: cloudant-secrets
        secret:
          secretName: binding-sample-java-cloudant-cloudantnosqldb
        
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: sprint-boot-app
  namespace: default
spec:
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30052
  selector:
    name: spring-boot-deployment
  type: NodePort
